### ISSUE TITLE
Log Issue

### ISSUE THREAD

**Issue by ryanpfister** [FrachlitzStudio/MessageLoggerBot#1]
C:\Users\ultim\OneDrive\Desktop\est1\MessageLoggerBot>node bot.js
I am alive!
(node:15944) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
    at C:\Users\ultim\OneDrive\Desktop\est1\MessageLoggerBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\ultim\OneDrive\Desktop\est1\MessageLoggerBot\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15944) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
    at C:\Users\ultim\OneDrive\Desktop\est1\MessageLoggerBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\ultim\OneDrive\Desktop\est1\MessageLoggerBot\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by FrachlitzStudio** [comment]
I'm not very good at it, but try this:
1. Give more rights to the bot.
2. Move his role up.
